print ("Juego piedra, papel o tijera.")
print ("  1. Los dos jugadores que van a jugar se sitúan uno frente al otro, con las manos en la espalda.")
print ("  2. Cuentan juntos hasta tres y extienden la mano en una de las tres posiciones siguientes:")
print ("     - Piedra")
print ("     - Papel")
print ("     - Tijera")
print ("  3. El elemento más fuerte suma un punto.")
print ("     - La piedra aplasta la tijera.")
print ("     - La tijera corta el papel.")
print ("     - El papel envuelve la piedra.")
print ("  4. Gana el primer jugador que sume 3 puntos.")
print ("  5. En caso de que dos jugadores elijan el mismo elemento se juega otra vez.")