print ("Herramientas")
print ("- Escoba")
print ("- Recogedor")
print ("- Contenedores de basura")
print ("Pasos")
print ("1. Seleccionar el área para limpieza.")
print ("2. Fijar el orden para iniciar limpieza desde el fondo hasta la salida.")
print ("3. Sujeta la escoba con ambas manos, colocando una mano arriba y la otra cerca del centro.") 
print ("4. Realiza movimientos desde lejos del cuerpo hacia adentro.")
print ("5. Las cerdas empujarán cualquier tipo de residuos que se encuentren en el suelo en la dirección en la que estés barriendo.")
print ("6. Hacer puntos de reunión de basura para agilizar el barrido.")
print ("7. Separar basura orgánica e inorgánica.")
print ("8. Haz una pausa de vez en cuando para limpiar la escoba, como el pelo y pelusas en las cerdas de la escoba.")
print ("9. Con el recogedor levantar la basura y depositarla en los contenedores correspondientes.")
